<?php
$lang = [
    'dir' => 'ltr',
    'dropdown_align' => 'right: 0;',
    'dashboard' => 'Dashboard',
    'about' => 'About',
    'alerts' => 'Alerts',
    'exit' => 'Exit',
    'admin' => 'admin panel ⚙️',
    'update_prof' => '👤 Update Profile',
    'gold_theme' => '👑 VIP Gold Theme',
    'dark_mode' => '🌙 Dark/Light Mode',
    'switch_lang_text' => '🌐 العربية',
    'switch_lang_link' => '?lang=ar',
    'welcome' => 'Welcome, ',
    'overview' => "Here's an overview of your activities",
    'progress' => 'Progress',
    'meals' => 'Meals',
    'workouts' => 'Workouts',
    'timeline' => 'Timeline',
    'tips' => 'Tips',
    'meal_plans' => 'Meal Plans',
    'challenges' => 'Challenges',
    'store' => 'Store',
    'step_tracker' => 'Step Tracker',
    'goal_weight_loss' => 'Lose Weight',
    'goal_muscle_gain' => 'Gain Muscle',
    'goal_fitness' => 'General Fitness',
    'meal_plans_title' => 'Personalized for you ✨',
    'fuel_body' => 'Fuel Your <span class="text-gradient">Body</span>',
    'hello' => 'Hello, ',
    'champion' => 'Champion',
    'based_on_goal' => 'Based on your goal to ',
    'curated_options' => ', here are your curated meal options for today.',
    'diet_type' => 'Diet Type:',
    'balanced' => '⚖️ Balanced',
    'low_carb' => '🥩 Low Carb',
    'keto' => '🥑 Keto',
    'health_filter' => 'Diabetes & Blood Pressure Friendly 🩺',
    'breakfast' => 'Breakfast',
    'lunch_dinner' => 'Lunch & Dinner',
    'snacks_desserts' => 'Snacks & Desserts',
    
    // كلمات صفحة الوجبات (Meals)
    'ai_meal_scan' => 'AI Meal Scan',
    'save' => 'Save',
    'food' => 'Food',
    'remaining' => 'Remaining',
    'over_limit' => 'Over Limit',
    'target' => 'Target: ',
    'water_intake' => 'Water Intake',
    'resets_daily' => 'Resets daily at 3:00 AM',
    'weekly_insights' => 'Weekly Insights',
    'add_food' => 'Add Food',
    'type' => 'Type',
    'food_name' => 'Food Name',
    'qty' => 'Qty',
    'kcal' => 'kcal',
    'protein_g' => 'Prot(g)',
    'fat_g' => 'Fat(g)',
    'carb_g' => 'Carb(g)',
    'add_from_plan' => 'Add from your meal plan',
    'log_meal' => 'Log',

    // كلمات صفحة التحديات (Challenges) ولوحة المتصدرين (Leaderboard)
    'challenges_arena' => 'Challenges Arena',
    'challenges_desc' => 'Complete challenges, earn Badges, and collect GlowCoins!',
    'glowcoins' => 'GlowCoins',
    'leaderboard' => 'Leaderboard',
    'progress_text' => 'Progress: ',
    'days_text' => 'days',
    'join_challenge' => 'Join Challenge',
    'claim_rewards' => 'Claim Rewards!',
    'log_daily_progress' => 'Log Daily Progress',
    'logged_today' => 'Logged Today',
    'top_champions' => '🏆 Top GlowWell Champions',
    'rank' => 'Rank',
    'name' => 'Name',
    'you' => '(You 🌟)',
    
    // تنبيهات الجافاسكريبت
    'js_great_progress' => 'Great Progress!',
    'js_keep_it_up' => 'Keep it up! Your dedication is glowing!',
    'js_awesome' => 'Awesome!',
    'js_great_job' => 'Great job! Your progress has been updated.',
    'js_already_logged' => 'You have already logged your progress for today!',
    // كلمات صفحة التمارين (Workouts) والـ AI
    'your_workout_plan' => 'Your Workout Plan',
    'ai_workout_plan' => 'AI Workout Plan',
    'open_btn' => 'Open',
    'start_btn' => 'Start',
    'start_timer' => 'Start Timer',
    'well_done' => 'Well Done! ✓',
    'workout_suggestions' => 'Workout suggestions',
    'choose_goal_ai' => 'Choose your goal and get an AI plan (Gemini).',
    'goal_label' => 'Goal',
    'choose_option' => '— Choose —',
    'suggest_btn' => 'Suggest',
    'from_gemini' => 'From Gemini',
    'fallback_plan' => 'Fallback plan:',
    'js_save_error' => 'Save error: ',
    'js_connection_failed' => 'Connection failed',
    'steps_title' => 'Instructions',
    'seconds_abbr' => 's',

    // --- الإضافات الجديدة لصفحات البروفايل ---
    'update_profile_title' => 'Update Profile',
    'setup_profile_title' => 'Setup Your Profile',
    'full_name' => 'Full Name',
    'email_address' => 'Email Address',
    'age' => 'Age',
    'height_cm' => 'Height (cm)',
    'weight_kg' => 'Weight (kg)',
    'gender_label' => 'Gender',
    'select_gender' => 'Select Gender',
    'male' => 'Male',
    'female' => 'Female',
    'health_goal_label' => 'Health Goal',
    'select_goal' => 'Select Goal',
    'goal_lose_weight' => 'Lose Weight',
    'goal_build_muscle' => 'Build Muscle',
    'activity_level_label' => 'Activity Level',
    'select_activity' => 'Select Activity Level',
    'sedentary' => 'Sedentary',
    'moderate' => 'Moderate',
    'active' => 'Active',
    'cancel' => 'Cancel',
    'save_changes' => 'Save Changes',
    'save_profile_btn' => 'Save Profile',
    'my_earned_badges' => 'My Earned Badges',
    'no_badges' => 'No badges earned yet. Keep challenging yourself!',
    'midnight_theme' => 'Midnight Gold Theme',
    'activate_theme' => 'Activate Theme',
    'deactivate_theme' => 'Deactivate Theme',
    'elite_challenger' => 'Elite Challenger',
    'global_badge' => 'Global Recognition Badge',
    'daily_tips' => 'Daily <span class="text-pink-600 drop-shadow-sm">Glow Tips ✨</span>',
    'personalized_advice' => 'Personalized advice for your',
    'journey' => 'journey',
    // أضيفي هذه الأسطر قبل إغلاق القوس ]
'progress_glow_details' => 'Your Glow Details',
'burned' => 'Burned',
'eaten' => 'Eaten',
'remaining_cal' => 'Remaining',
'weight_lbl' => 'Weight',
'weekly_progress' => 'Weekly Progress',
'workout_btn' => 'Let\'s Work Out!',
'no_activities' => 'No activities found.',

    // steps_tracker.php
    'steps_tracker.title' => 'Steps Tracker',
    'steps_tracker.track_daily' => 'Track your daily steps',
    'steps_tracker.steps_today' => 'Steps Today',
    'steps_tracker.goal' => 'Goal: ',
    'steps_tracker.steps' => ' Steps',
    'steps_tracker.completed' => ' Completed',
    'steps_tracker.sync_steps' => 'Sync Steps',
    'steps_tracker.add_steps' => '+ Add Steps',
    'steps_tracker.steps_this_week' => 'Steps This Week',
    'steps_tracker.goal_reached' => '🎉 Goal Reached! Keep going!',
    'steps_tracker.keep_walking' => 'Keep walking! Your extra steps are being tracked and will be added to today\'s total.',
    'steps_tracker.steps_synced' => ' steps synced!',
    'steps_tracker.error' => '⚠️ Error: ',
    'steps_tracker.unknown_error' => 'Unknown error',
    'steps_tracker.failed_server' => '⚠️ Failed to connect to server.',
    'steps_tracker.ios_tap' => 'Tap anywhere to enable step tracking on iOS.',
    'steps_tracker.mobile_only' => 'Step tracking is only available on supported mobile devices.',

    // timeline.php
    'timeline.title' => 'Daily Timeline',
    'timeline.showing_logs' => 'Showing logs for: ',
    'timeline.nothing_logged' => 'Nothing logged',
    'timeline.delete_confirm' => 'Delete this meal?',
    'timeline.hydration' => 'Hydration Progress',
    'timeline.glasses' => 'Glasses',
    'timeline.goal_2l' => 'Goal: 2 Liters per day',
    'timeline.breakfast' => 'Breakfast',
    'timeline.lunch' => 'Lunch',
    'timeline.workout' => 'Workout',
    'timeline.dinner' => 'Dinner',
    'timeline.snacks' => 'Snacks',

    // notifications.php
    'notifications.title' => 'Notifications',
    'notifications.missing_dinner_title' => 'Missing Dinner?',
    'notifications.missing_dinner_desc' => 'You haven\'t logged your dinner yet. Try a low-carb option!',
    'notifications.workout_suggest' => 'Your daily routine',
    'notifications.workout_time_title' => 'Time for a workout',
    'notifications.workout_time_desc' => 'You haven\'t exercised yet today! Stay active with: ',
    'notifications.reminder_title' => 'Reminder',
    'notifications.reminder_desc' => 'Don\'t forget to drink 2L of water today.',

    // Days of the week (Abbreviations)
    'Mon' => 'Mon',
    'Tue' => 'Tue',
    'Wed' => 'Wed',
    'Thu' => 'Thu',
    'Fri' => 'Fri',
    'Sat' => 'Sat',
    'Sun' => 'Sun',

    // Chart Y-axis
    'chart.10k' => '10k',
    'chart.8k' => '8k',
    'chart.6k' => '6k',
    'chart.4k' => '4k',
    'chart.2k' => '2k',
    'chart.0' => '0',
];
?>