<?php
$lang = [
    'dir' => 'rtl',
    'dropdown_align' => 'left: 0;',
    'dashboard' => 'الرئيسية',
    'about' => 'عن الموقع',
    'alerts' => 'التنبيهات',
    'exit' => 'خروج',
    'admin' => 'لوحة التحكم ⚙️',
    'update_prof' => '👤 تحديث الحساب',
    'gold_theme' => '👑 الثيم الذهبي VIP',
    'dark_mode' => '🌙 الوضع الليلي/النهاري',
    'switch_lang_text' => '🌐 English',
    'switch_lang_link' => '?lang=en',
    'welcome' => 'أهلاً بك، ',
    'overview' => 'إليك نظرة عامة على نشاطاتك',
    'progress' => 'التقدم',
    'meals' => 'الوجبات',
    'workouts' => 'التمارين',
    'timeline' => 'الجدول الزمني',
    'tips' => 'نصائح',
    'meal_plans' => 'خطة الوجبات',
    'challenges' => 'التحديات',
    'store' => 'المتجر',
    'step_tracker' => 'مراقب الخطوات',
    'goal_weight_loss' => 'خسارة الوزن',
    'goal_muscle_gain' => 'بناء العضلات',
    'goal_fitness' => 'اللياقة العامة',
    'meal_plans_title' => 'مخصص لك خصيصاً ✨',
    'fuel_body' => 'غَذِّ <span class="text-gradient">جسمك</span>',
    'hello' => 'أهلاً، ',
    'champion' => 'بطل',
    'based_on_goal' => 'بناءً على هدفك في <strong>',
    'curated_options' => '</strong>، إليك خيارات الوجبات المختارة لك اليوم.',
    'diet_type' => 'نوع النظام:',
    'balanced' => '⚖️ متوازن',
    'low_carb' => '🥩 كارب منخفض',
    'keto' => '🥑 كيتو',
    'health_filter' => 'مناسب لمرضى السكري والضغط 🩺',
    'breakfast' => 'الإفطار',
    'lunch_dinner' => 'الغداء والعشاء',
    'snacks_desserts' => 'سناك وحلويات',

    // كلمات صفحة الوجبات (Meals)
    'ai_meal_scan' => 'مسح الوجبة بالذكاء الاصطناعي',
    'save' => 'حفظ',
    'food' => 'الطعام',
    'remaining' => 'المتبقي',
    'over_limit' => 'تجاوز الحد',
    'target' => 'الهدف: ',
    'water_intake' => 'استهلاك الماء',
    'resets_daily' => 'يتحدث يومياً الساعة 3:00 ص',
    'weekly_insights' => 'إحصائيات الأسبوع',
    'add_food' => 'إضافة طعام',
    'type' => 'النوع',
    'food_name' => 'اسم الطعام',
    'qty' => 'الكمية',
    'kcal' => 'سعرات',
    'protein_g' => 'بروتين (غ)',
    'fat_g' => 'دهون (غ)',
    'carb_g' => 'كارب (غ)',
    'add_from_plan' => 'إضافة من خطتك',
    'log_meal' => 'تسجيل',

    // كلمات صفحة التحديات (Challenges) ولوحة المتصدرين (Leaderboard)
    'challenges_arena' => 'ساحة التحديات',
    'challenges_desc' => 'أكمل التحديات، واكسب الأوسمة، واجمع عملات GlowCoins!',
    'glowcoins' => 'عملات Glow',
    'leaderboard' => 'لوحة المتصدرين',
    'progress_text' => 'التقدم: ',
    'days_text' => 'أيام',
    'join_challenge' => 'انضم للتحدي',
    'claim_rewards' => 'استلم المكافأة!',
    'log_daily_progress' => 'سجل تقدمك اليومي',
    'logged_today' => 'تم التسجيل اليوم',
    'top_champions' => '🏆 أبطال GlowWell',
    'rank' => 'المركز',
    'name' => 'الاسم',
    'you' => '(أنت 🌟)',
    
    // تنبيهات الجافاسكريبت
    'js_great_progress' => 'تقدم رائع!',
    'js_keep_it_up' => 'استمر! إصرارك متألق!',
    'js_awesome' => 'رائع!',
    'js_great_job' => 'عمل رائع! تم تحديث تقدمك.',
    'js_already_logged' => 'لقد قمت بتسجيل تقدمك لهذا اليوم مسبقاً!',
    // كلمات صفحة التمارين (Workouts) والـ AI
    'your_workout_plan' => 'خطة تمارينك',
    'ai_workout_plan' => 'خطة تمارين ذكية',
    'open_btn' => 'فتح',
    'start_btn' => 'ابدأ',
    'start_timer' => 'بدء المؤقت',
    'well_done' => 'أحسنت! ✓',
    'workout_suggestions' => 'اقتراحات التمارين',
    'choose_goal_ai' => 'اختر هدفك واحصل على خطة ذكاء اصطناعي (Gemini).',
    'goal_label' => 'الهدف',
    'choose_option' => '— اختر —',
    'suggest_btn' => 'اقترح',
    'from_gemini' => 'من Gemini',
    'fallback_plan' => 'الخطة البديلة:',
    'js_save_error' => 'حدث خطأ في الحفظ: ',
    'js_connection_failed' => 'فشل الاتصال بالسيرفر',
    'steps_title' => 'التعليمات',
    'seconds_abbr' => 'ثانية',

    // --- الإضافات الجديدة لصفحات البروفايل ---
    'update_profile_title' => 'تحديث الحساب',
    'setup_profile_title' => 'إعداد حسابك',
    'full_name' => 'الاسم الكامل',
    'email_address' => 'البريد الإلكتروني',
    'age' => 'العمر',
    'height_cm' => 'الطول (سم)',
    'weight_kg' => 'الوزن (كغ)',
    'gender_label' => 'الجنس',
    'select_gender' => 'اختر الجنس',
    'male' => 'ذكر',
    'female' => 'أنثى',
    'health_goal_label' => 'الهدف الصحي',
    'select_goal' => 'اختر الهدف',
    'goal_lose_weight' => 'خسارة الوزن',
    'goal_build_muscle' => 'بناء العضلات',
    'activity_level_label' => 'مستوى النشاط',
    'select_activity' => 'اختر مستوى النشاط',
    'sedentary' => 'خامل (قليل الحركة)',
    'moderate' => 'معتدل (نشاط متوسط)',
    'active' => 'نشط (كثير الحركة)',
    'cancel' => 'إلغاء',
    'save_changes' => 'حفظ التغييرات',
    'save_profile_btn' => 'حفظ الحساب',
    'my_earned_badges' => 'أوسمتي المكتسبة',
    'no_badges' => 'لم تكسب أي أوسمة بعد. استمر في التحدي!',
    'midnight_theme' => 'ثيم منتصف الليل الذهبي',
    'activate_theme' => 'تفعيل الثيم',
    'deactivate_theme' => 'إلغاء تفعيل الثيم',
    'elite_challenger' => 'متحدي النخبة',
    'global_badge' => 'وسام التميز العالمي',
    'daily_tips' => 'نصائح <span class="text-pink-600 drop-shadow-sm">Glow اليومية ✨</span>',
    'personalized_advice' => 'نصائح مخصصة لـ',
    'journey' => 'رحلتك في',
    // أضيفي هذه الأسطر قبل إغلاق القوس ]
'progress_glow_details' => 'تفاصيل توهجك',
'burned' => 'المحروق',
'eaten' => 'المأكول',
'remaining_cal' => 'المتبقي',
'weight_lbl' => 'الوزن',
'weekly_progress' => 'التقدم الأسبوعي',
'workout_btn' => 'لنمارس الرياضة!',
'no_activities' => 'لا توجد أنشطة مسجلة.',

    // steps_tracker.php
    'steps_tracker.title' => 'مراقب الخطوات',
    'steps_tracker.track_daily' => 'تتبع خطواتك اليومية',
    'steps_tracker.steps_today' => 'خطوات اليوم',
    'steps_tracker.goal' => 'الهدف: ',
    'steps_tracker.steps' => ' خطوة',
    'steps_tracker.completed' => ' مكتمل',
    'steps_tracker.sync_steps' => 'مزامنة الخطوات',
    'steps_tracker.add_steps' => '+ إضافة خطوات',
    'steps_tracker.steps_this_week' => 'خطوات هذا الأسبوع',
    'steps_tracker.goal_reached' => '🎉 تم الوصول للهدف! استمر في التقدم!',
    'steps_tracker.keep_walking' => 'استمر في المشي! يتم تتبع خطواتك الإضافية وستتم إضافتها إلى إجمالي اليوم.',
    'steps_tracker.steps_synced' => ' خطوة تمت مزامنتها!',
    'steps_tracker.error' => '⚠️ خطأ: ',
    'steps_tracker.unknown_error' => 'خطأ غير معروف',
    'steps_tracker.failed_server' => '⚠️ فشل الاتصال بالخادم.',
    'steps_tracker.ios_tap' => 'اضغط في أي مكان لتفعيل تتبع الخطوات على iOS.',
    'steps_tracker.mobile_only' => 'تتبع الخطوات متاح فقط على الأجهزة المحمولة المدعومة.',

    // timeline.php
    'timeline.title' => 'الجدول الزمني اليومي',
    'timeline.showing_logs' => 'عرض السجلات لـ: ',
    'timeline.nothing_logged' => 'لم يتم تسجيل شيء',
    'timeline.delete_confirm' => 'هل تريد حذف هذه الوجبة؟',
    'timeline.hydration' => 'تقدم شرب الماء',
    'timeline.glasses' => 'أكواب',
    'timeline.goal_2l' => 'الهدف: 2 لتر يومياً',
    'timeline.breakfast' => 'الإفطار',
    'timeline.lunch' => 'الغداء',
    'timeline.workout' => 'التمرين',
    'timeline.dinner' => 'العشاء',
    'timeline.snacks' => 'سناك',

    // notifications.php
    'notifications.title' => 'التنبيهات',
    'notifications.missing_dinner_title' => 'هل نسيت العشاء؟',
    'notifications.missing_dinner_desc' => 'لم تقم بتسجيل عشائك بعد. جرب خياراً منخفض الكربوهيدرات!',
    'notifications.workout_suggest' => 'روتينك اليومي',
    'notifications.workout_time_title' => 'وقت التمرين',
    'notifications.workout_time_desc' => 'لم تتمرن اليوم بعد! حافظ على نشاطك مع: ',
    'notifications.reminder_title' => 'تذكير',
    'notifications.reminder_desc' => 'لا تنس شرب 2 لتر من الماء اليوم.',

    // Days of the week (Abbreviations)
    'Mon' => 'الأثنين',
    'Tue' => 'الثلاثاء',
    'Wed' => 'الأربعاء',
    'Thu' => 'الخميس',
    'Fri' => 'الجمعة',
    'Sat' => 'السبت',
    'Sun' => 'الأحد',

    // Chart Y-axis
    'chart.10k' => '١٠ آلاف',
    'chart.8k' => '٨ آلاف',
    'chart.6k' => '٦ آلاف',
    'chart.4k' => '٤ آلاف',
    'chart.2k' => '٢ آلاف',
    'chart.0' => '٠',
];
?>